combineFigs('scatter_case_streamline_count.fig', 'scatter_ctrl_streamline_count.fig', '/scratch/lliu/SPINS/analysis/figures/scatter_comb_streamline_count.fig')
combineFigs('scatter_case_length.fig', 'scatter_ctrl_length.fig', '/scratch/lliu/SPINS/analysis/figures/scatter_comb_length.fig')
combineFigs('scatter_case_fa_mean.fig', 'scatter_ctrl_fa_mean.fig', '/scratch/lliu/SPINS/analysis/figures/scatter_comb_fa_mean.fig')
combineFigs('scatter_case_md_mean.fig', 'scatter_ctrl_md_mean.fig', '/scratch/lliu/SPINS/analysis/figures/scatter_comb_md_mean.fig')
combineFigs('scatter_case_length_weighted.fig', 'scatter_ctrl_length_weighted.fig', '/scratch/lliu/SPINS/analysis/figures/scatter_comb_length_weighted.fig')
combineFigs('scatter_case_volume_weighted.fig', 'scatter_ctrl_volume_weighted.fig', '/scratch/lliu/SPINS/analysis/figures/scatter_comb_volume_weighted.fig')

% combineFigs('binning_case_streamline_count.fig', 'binning_ctrl_streamline_count.fig', '/scratch/lliu/SPINS/analysis/figures/binning_comb_streamline_count.fig')
% combineFigs('binning_case_length.fig', 'binning_ctrl_length.fig', '/scratch/lliu/SPINS/analysis/figures/binning_comb_length.fig')
% combineFigs('binning_case_fa_mean.fig', 'binning_ctrl_fa_mean.fig', '/scratch/lliu/SPINS/analysis/figures/binning_comb_fa_mean.fig')
% combineFigs('binning_case_md_mean.fig', 'binning_ctrl_md_mean.fig', '/scratch/lliu/SPINS/analysis/figures/binning_comb_md_mean.fig')
% combineFigs('binning_case_length_weighted.fig', 'binning_ctrl_length_weighted.fig', '/scratch/lliu/SPINS/analysis/figures/binning_comb_length_weighted.fig')
% combineFigs('binning_case_volume_weighted.fig', 'binning_ctrl_volume_weighted.fig', '/scratch/lliu/SPINS/analysis/figures/binning_comb_volume_weighted.fig')
